path: ........./Preprocessing_MLCPS/yolo_B/data  # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Classes
names:
  0: B
